### ISSUE TITLE
Running `deriveLift` recursively

### ISSUE THREAD

**Issue by ChaiTRex** [RyanGlScott/th-lift#36]
When trying to do <code>deriveLift ''[DynFlags](https://hackage.haskell.org/package/ghc-8.4.3/docs/DynFlags.html#t:DynFlags)</code>, I have to keep deriving `Lift` for more and more types. It would be nice if there was a way for `deriveLift` to recursively derive `Lift` instances for types contained within types (if those types don't already have an instance).

**Comment by RyanGlScott** [comment]
The [`th-reify-many`](http://hackage.haskell.org/package/th-reify-many-0.1.9/docs/Language-Haskell-TH-ReifyMany.html) library provides this functionality in a class-agnostic way. An example of how to combine it with `deriveLift` can be found [here](https://github.com/mgsloan/th-orphans/blob/6a3c1f8c48dca9d06bdec3019ea23256e7432c24/src/Language/Haskell/TH/Instances.hs#L433-L434).

**Comment by RyanGlScott** [comment]
Closing as out-of-scope.
